- Author:
    Name: Jann
    Handle: '@jannlemm0913'
    Link: https://avantguard.io
  Name: ListThreads
  Aliases: []
  Description: Enumerates threads and their states in a specified process.
  Help: >-
    Returns the Thread ID, StartAddress and State of the threads in the specified process.


    This is simply done via Process.GetProcessById() and Threads.

    If the thread is in a waiting state, the wait reason will be appended to the output.
  Language: CSharp
  CompatibleDotNetVersions:
  - Net35
  - Net40
  Code: >-
    using System;

    using System.IO;

    using System.Diagnostics;


    public static class Task

    {
        public static string Execute(string ProcessId)
        {
            int pid = int.Parse(ProcessId);
            string output = " Thread ID | StartAddress       | State                        \n---------------------------------------------------------------\n";
            try
            {
                ProcessThreadCollection myThreads = Process.GetProcessById(pid).Threads;

                foreach (ProcessThread pt in myThreads)
                {
                    string state = pt.ThreadState.ToString();
                    output += pt.Id.ToString().PadRight(10) + "| 0x" + pt.StartAddress.ToString("X16") + " | " + state;

                    if(state == "Wait")
                    {
                        output += ":" + pt.WaitReason.ToString() + "\n";
                    } else {
                        output += "\n";
                    }
                }
                 return output;
            }
            catch (Exception e) { return e.GetType().FullName + ": " + e.Message + Environment.NewLine + e.StackTrace; }
        }
    }
  Compiled: false
  TaskingType: Assembly
  ReferenceSourceLibraries: []
  ReferenceAssemblies:
  - Name: System.Core.dll
    Location: net35/System.Core.dll
    DotNetVersion: Net35
  - Name: System.dll
    Location: net35/System.dll
    DotNetVersion: Net35
  - Name: mscorlib.dll
    Location: net35/mscorlib.dll
    DotNetVersion: Net35
  - Name: System.Core.dll
    Location: net40/System.Core.dll
    DotNetVersion: Net40
  - Name: System.dll
    Location: net40/System.dll
    DotNetVersion: Net40
  - Name: mscorlib.dll
    Location: net40/mscorlib.dll
    DotNetVersion: Net40
  EmbeddedResources: []
  UnsafeCompile: false
  TokenTask: false
  Options:
  - Name: ProcessID
    Value: 8376
    DefaultValue: ''
    Description: The Process ID of the process to enumerate.
    SuggestedValues: []
    Optional: false
    DisplayInCommand: true
    FileOption: false
    GruntTaskId: 108
