- Author:
    Name: Ryan Cobb
    Handle: cobbr_io
    Link: https://twitter.com/cobbr_io
  Name: ProcessList
  Aliases:
  - ps
  Description: Get a list of currently running processes.
  Help: 
  Language: CSharp
  CompatibleDotNetVersions:
  - Net35
  - Net40
  Code: >
    using System;

    using System.Linq;


    using SharpSploit.Enumeration;


    public static class Task

    {
        public static string Execute(string SearchString = "")
        {
            try
            {
                string output = "Pid    Ppid  Name                             SessionID  Owner                Architecture  Path\n---    ----  ----                             ---------  -----                ------------  ----\n";
                string defaultOutput = Host.GetProcessList().ToString();
                string[] completeList = defaultOutput.Split('\n');
                if(!string.IsNullOrEmpty(SearchString)){
                    foreach (string line in completeList) {
                        if (line?.IndexOf(SearchString, StringComparison.OrdinalIgnoreCase) >= 0)
                        {
                            output += line + "\n";
                        }
                    }
                } else {
                    return defaultOutput;
                }
                return output;
                //return Host.GetProcessList().ToString();
            }
            catch (Exception e) { return e.GetType().FullName + ": " + e.Message + Environment.NewLine + e.StackTrace; }
        }
    }
  Compiled: false
  TaskingType: Assembly
  ReferenceSourceLibraries:
  - Name: SharpSploit
    Description: SharpSploit is a library for C# post-exploitation modules.
    Location: SharpSploit/SharpSploit/
    Language: CSharp
    CompatibleDotNetVersions:
    - Net35
    - Net40
    ReferenceAssemblies:
    - Name: System.dll
      Location: net40/System.dll
      DotNetVersion: Net40
    - Name: System.ServiceProcess.dll
      Location: net40/System.ServiceProcess.dll
      DotNetVersion: Net40
    - Name: System.ServiceProcess.dll
      Location: net35/System.ServiceProcess.dll
      DotNetVersion: Net35
    - Name: System.Windows.Forms.dll
      Location: net40/System.Windows.Forms.dll
      DotNetVersion: Net40
    - Name: System.Windows.Forms.dll
      Location: net35/System.Windows.Forms.dll
      DotNetVersion: Net35
    - Name: System.Management.Automation.dll
      Location: net40/System.Management.Automation.dll
      DotNetVersion: Net40
    - Name: System.Management.Automation.dll
      Location: net35/System.Management.Automation.dll
      DotNetVersion: Net35
    - Name: System.Management.dll
      Location: net40/System.Management.dll
      DotNetVersion: Net40
    - Name: System.Management.dll
      Location: net35/System.Management.dll
      DotNetVersion: Net35
    - Name: System.IdentityModel.dll
      Location: net40/System.IdentityModel.dll
      DotNetVersion: Net40
    - Name: System.IdentityModel.dll
      Location: net35/System.IdentityModel.dll
      DotNetVersion: Net35
    - Name: System.DirectoryServices.Protocols.dll
      Location: net40/System.DirectoryServices.Protocols.dll
      DotNetVersion: Net40
    - Name: System.DirectoryServices.Protocols.dll
      Location: net35/System.DirectoryServices.Protocols.dll
      DotNetVersion: Net35
    - Name: System.DirectoryServices.dll
      Location: net40/System.DirectoryServices.dll
      DotNetVersion: Net40
    - Name: System.DirectoryServices.dll
      Location: net35/System.DirectoryServices.dll
      DotNetVersion: Net35
    - Name: System.Core.dll
      Location: net40/System.Core.dll
      DotNetVersion: Net40
    - Name: System.Core.dll
      Location: net35/System.Core.dll
      DotNetVersion: Net35
    - Name: mscorlib.dll
      Location: net35/mscorlib.dll
      DotNetVersion: Net35
    - Name: mscorlib.dll
      Location: net40/mscorlib.dll
      DotNetVersion: Net40
    - Name: System.dll
      Location: net35/System.dll
      DotNetVersion: Net35
    - Name: System.XML.dll
      Location: net35/System.XML.dll
      DotNetVersion: Net35
    - Name: System.XML.dll
      Location: net40/System.XML.dll
      DotNetVersion: Net40
    EmbeddedResources: []
  ReferenceAssemblies: []
  EmbeddedResources: []
  UnsafeCompile: false
  TokenTask: false
  Options:
  - Name: SearchString
    Value: ''
    DefaultValue: ''
    Description: Filter for a specified string.
    SuggestedValues: []
    Optional: true
    DisplayInCommand: false
    FileOption: false
    GruntTaskId: 65
