- Author:
    Name: Will Schroeder
    Handle: harmj0y
    Link: https://twitter.com/harmj0y
  Name: Rubeus
  Aliases: []
  Description: Use a rubeus command.
  Help: 
  Language: CSharp
  CompatibleDotNetVersions:
  - Net40
  Code: "using System;\nusing System.IO;\n\nusing Rubeus.Domain;\n\npublic static class Task\n{\n    public static Stream OutputStream { get; set; }\n    public static string Execute(string Command)\n    {\n        try\n        {\n            TextWriter realStdOut = Console.Out;\n            TextWriter realStdErr = Console.Error;\n            StreamWriter stdOutWriter = new StreamWriter(OutputStream);\n            StreamWriter stdErrWriter = new StreamWriter(OutputStream);\n            stdOutWriter.AutoFlush = true;\n            stdErrWriter.AutoFlush = true;\n            Console.SetOut(stdOutWriter);\n            Console.SetError(stdErrWriter);\n            \n            string[] args = Command.Split(' ');\n            try\n            {\n                Info.ShowLogo();\n\n                // try to parse the command line arguments, show usage on failure and then bail\n                var parsed = ArgumentParser.Parse(args);\n                if (parsed.ParsedOk == false)\n                {\n                    Info.ShowUsage();\n                }\n                else\n                {\n                    // Try to execute the command using the arguments passed in\n\n                    var commandName = args.Length != 0 ? args[0] : \"\";\n\n                    var commandFound = new CommandCollection().ExecuteCommand(commandName, parsed.Arguments);\n\n                    // show the usage if no commands were found for the command name\n                    if (commandFound == false)\n                        Info.ShowUsage();\n                }\n            }\n            catch (Exception e)\n            {\n                Console.WriteLine(\"\\r\\n[!] Unhandled Rubeus exception:\\r\\n\");\n                Console.WriteLine(e);\n            }\n            \n            Console.Out.Flush();\n            Console.Error.Flush();\n            Console.SetOut(realStdOut);\n            Console.SetError(realStdErr);\n            \n            OutputStream.Close();\n            return \"\";\n        }\n        catch (Exception e)\n        {\n          if (OutputStream != null)\n          {\n            OutputStream.Close();\n          }\n          return e.GetType().FullName + \": \" + e.Message + Environment.NewLine + e.StackTrace;\n        }\n    }\n}\n"
  Compiled: false
  TaskingType: Assembly
  ReferenceSourceLibraries:
  - Name: Rubeus
    Description: Rubeus is a C# toolset for raw Kerberos interaction and abuses.
    Location: Rubeus/
    Language: CSharp
    CompatibleDotNetVersions:
    - Net40
    ReferenceAssemblies:
    - Name: System.IdentityModel.dll
      Location: net40/System.IdentityModel.dll
      DotNetVersion: Net40
    - Name: System.IdentityModel.dll
      Location: net35/System.IdentityModel.dll
      DotNetVersion: Net35
    - Name: System.DirectoryServices.AccountManagement.dll
      Location: net40/System.DirectoryServices.AccountManagement.dll
      DotNetVersion: Net40
    - Name: System.DirectoryServices.AccountManagement.dll
      Location: net35/System.DirectoryServices.AccountManagement.dll
      DotNetVersion: Net35
    - Name: System.DirectoryServices.dll
      Location: net40/System.DirectoryServices.dll
      DotNetVersion: Net40
    - Name: System.DirectoryServices.dll
      Location: net35/System.DirectoryServices.dll
      DotNetVersion: Net35
    - Name: System.Core.dll
      Location: net40/System.Core.dll
      DotNetVersion: Net40
    - Name: System.Core.dll
      Location: net35/System.Core.dll
      DotNetVersion: Net35
    - Name: System.dll
      Location: net40/System.dll
      DotNetVersion: Net40
    - Name: System.dll
      Location: net35/System.dll
      DotNetVersion: Net35
    - Name: mscorlib.dll
      Location: net40/mscorlib.dll
      DotNetVersion: Net40
    - Name: mscorlib.dll
      Location: net35/mscorlib.dll
      DotNetVersion: Net35
    EmbeddedResources: []
  ReferenceAssemblies:
  - Name: System.Data.dll
    Location: net40/System.Data.dll
    DotNetVersion: Net40
  - Name: System.Security.dll
    Location: net40/System.Security.dll
    DotNetVersion: Net40
  - Name: System.Data.DataSetExtensions.dll
    Location: net40/System.Data.DataSetExtensions.dll
    DotNetVersion: Net40
  - Name: System.DirectoryServices.Protocols.dll
    Location: net40/System.DirectoryServices.Protocols.dll
    DotNetVersion: Net40
  - Name: System.XML.dll
    Location: net40/System.XML.dll
    DotNetVersion: Net40
  EmbeddedResources: []
  UnsafeCompile: true
  TokenTask: false
  Options:
  - Name: Command
    Value: triage
    DefaultValue: ''
    Description: Rubeus command to execute.
    SuggestedValues:
    - triage
    - dump
    - asktgt
    - asktgs
    - renew
    - s4u
    - ptt
    - purge
    - describe
    - klist
    - tgtdeleg
    - monitor
    - harvest
    - kerberoast
    - asreproast
    - createnetonly
    - changepw
    - hash
    - tgssub
    Optional: true
    DisplayInCommand: true
    FileOption: false
    GruntTaskId: 97
